### ISSUE TITLE
Server is running... 以后发动消息给机器人投稿 提示。。。。

### ISSUE THREAD

**Issue by 641221621** [axiref/telegram-pwsbot#8]
(node:4199) UnhandledPromiseRejectionWarning: Error: ETELEGRAM: 400 Bad Request: chat_id is empty
    at /root/telegram-pwsbot/node_modules/node-telegram-bot-api/src/telegram.js:280:15
    at tryCatcher (/root/telegram-pwsbot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/telegram-pwsbot/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/root/telegram-pwsbot/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/telegram-pwsbot/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/telegram-pwsbot/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/root/telegram-pwsbot/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/root/telegram-pwsbot/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/root/telegram-pwsbot/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/telegram-pwsbot/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
(node:4199) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4199) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by 641221621** [comment]
![image](https://user-images.githubusercontent.com/19586730/118243892-89eb5d00-b4d1-11eb-87e6-4586b9cf97fb.png)

**Comment by zyh001** [comment]
@641221621 你的nodejs版本是？

**Comment by ssuyoungwu** [comment]
> @641221621 你的nodejs版本是？

请问应该用哪个版本的nodejs，babel的版本也有要求吗
我使用15.0.0的nodejs在运行
“babel src --out-dir dist --source-maps inline && cp -r src/lang dist”这句时碰到了“系统找不到指定的文件”的错误，请问应该如何解决，感激不尽
